//! Skill / slash-command file body that ships with `crux setup
//! claude-code`. Written to `~/.claude/commands/crux.md` so the user
//! can type `/crux` inside Claude Code to remind the model how to use
//! the CRUX MCP toolset.
//!
//! The body is plain Markdown with a YAML front-matter block describing
//! the slash command itself.

pub const CLAUDE_CODE_SKILL: &str = r#"---
description: How to use CRUX (token-optimization runtime) effectively in this project.
---

# /crux — CRUX integration helper

When this slash-command is invoked, you (the model) are reminded that
the [CRUX](https://github.com/Keradd/crux) MCP server is registered for
this project. CRUX exposes eleven tools that reduce token usage 60–95%
across the typical "Read → grep → think → Edit" loop. Prefer them over
the built-in Read / Glob / Grep tools whenever appropriate.

## Tool inventory

| MCP tool | Layer | What it does |
|---|---|---|
| `crux_remember` | L8 | Persist an observation (decision / fact / lesson). Survives across sessions. |
| `crux_recall` | L8 | FTS5 + decay-ranked search across past observations. |
| `crux_search` | L6 | Hybrid BM25 + dense + RRF search across code / prose / memory chunks. |
| `crux_find_symbol` | L5 | Locate symbols by name / substring / kind. |
| `crux_get_symbol_source` | L5 | Return the source body for a qualified symbol name. |
| `crux_query_graph` | L5 | List callers / callees of a symbol. |
| `crux_impact` | L5 | BFS blast radius from a seed symbol. |
| `crux_read` | L4 | Cache-aware file read; returns content / digest / delta. |
| `crux_bash_filter` | L3 | Apply CRUX's TOML-defined bash output filters to a `(command, output)` pair. |
| `crux_execute` | L7 | Run python / bash / node snippet inside a sandbox. |
| `crux_audit` | L9 | Health snapshot + telemetry summary. |

## How to pick the right tool

1. **"Where is X defined?"** → `crux_find_symbol` first, fall back to `crux_search` on a miss.
2. **"What calls / uses Y?"** → `crux_query_graph` (callers / callees) or `crux_impact` (transitive blast radius).
3. **"Show me the source of `foo::bar::baz`"** → `crux_get_symbol_source`.
4. **Free-text or fuzzy lookup** → `crux_search` (hybrid BM25 + dense + RRF; handles typos).
5. **Read a file** → prefer `crux_read` over the built-in Read tool. After the first read, repeats return digests / deltas instead of full bodies.
6. **Run a snippet** (Python / Bash / Node) → `crux_execute`. Has timeouts, output caps, env scrubbing, and optional rlimits / landlock / seccomp on Linux.
7. **Persist a non-trivial decision or finding for next session** → `crux_remember` with `kind = "decision"` / `"fact"` / `"lesson"` and a 1-line title.
8. **Re-find an earlier persisted observation** → `crux_recall <query>`.

## One-time setup checks

If `crux_search` or `crux_find_symbol` returns empty results, the project may
not be indexed yet. Ask the user (or run yourself) **once**:

```bash
crux index    # AST graph (Layer 5). ~2 s cold, ~200 ms warm.
crux reindex  # hybrid-search chunks (Layer 6). ~2.5 s cold, ~50 ms warm.
```

Both are Merkle-incremental, so subsequent runs are nearly free.

## When NOT to use CRUX tools

- Trivial reads of files the user just modified — the built-in Read may be fine.
- Symbols that don't appear in the AST graph yet (untracked language) — fall back
  to `crux_search` or the built-in Grep.
- Pure prose (READMEs, design docs) — `crux_search --kind prose` works, but
  inline grep is also fine.

## Integration entry points (FYI)

- MCP server registered at `mcpServers.crux` in your Claude Code settings.
- Hooks: `PreToolUse(Read)` and `PostToolUse(Edit|Write|MultiEdit)` route
  through `crux hook pre-tool` / `post-tool` to feed the L4 read cache.
- Project scaffolding (`CLAUDE.md`, `.crux/`, `.claudeignore`) is created
  by `crux init`. Re-run with `--force` to refresh.

This file was generated by `crux setup claude-code`. Re-run with
`--force` to overwrite.
"#;
