//! Render L8 memory as a `MEMORY.md` markdown view that OpenClaw /

use std::fs;
use std::io::Write;
use std::path::{Path, PathBuf};

use chrono::DateTime;

use crux_core::error::{CruxError, Result};

use crate::types::{Observation, ObservationKind};
use crate::MemoryEngine;

/// Marker line that identifies a CRUX-generated `MEMORY.md`. We refuse
/// to overwrite a file that doesn't carry this header so a misconfigured
/// project doesn't trash a hand-written `MEMORY.md`.
pub const GENERATED_HEADER: &str = "<!-- generated by crux memory export — DO NOT EDIT -->";

/// Hard cap on observations rendered into a single `MEMORY.md`. Keeps
/// the file from blowing past the agent's startup token budget when
/// L8 has thousands of decayed observations. Override per-call via
/// [`ExportOptions::limit`].
pub const DEFAULT_EXPORT_LIMIT: usize = 200;

/// Outcome of an [`export_memory_md`] call.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ExportReport {
    pub target: PathBuf,
    pub observations_rendered: usize,
    pub bytes_written: u64,
    /// True when the file already had the same byte content; we skip the
    /// write so debounced/repeated exports don't churn mtime.
    pub unchanged: bool,
    /// True when the existing file was a hand-written `MEMORY.md` (no
    /// generated header) and we refused to overwrite it.
    pub refused_due_to_handwritten: bool,
}

/// Per-call knobs. Defaults are safe for the common path — agents don't
/// need to set anything.
#[derive(Debug, Clone, Default)]
pub struct ExportOptions {
    /// Max observations to render. `None` => [`DEFAULT_EXPORT_LIMIT`].
    pub limit: Option<usize>,
    /// Force-overwrite even if the existing file looks hand-written.
    /// Use with care — this destroys data without a backup.
    pub force: bool,
}

// Pure render

/// Render observations as a fully-formed `MEMORY.md` document.
///
/// Output is **deterministic**: same input → byte-equal output (modulo
/// `generated_at`, which is included in the header for human reference
/// only and does not affect ordering or grouping).
///
/// Observations are grouped by [`ObservationKind`] in a fixed order
/// (Guardrail → User → Convention → Decision → Project → Reference →
/// ErrorPattern → Feedback) and within each group sorted by importance
/// desc, then by id desc as a tiebreaker.
pub fn render_memory_md(
    observations: &[Observation],
    project_root: &str,
    generated_at_epoch: i64,
) -> String {
    let mut out = String::new();
    out.push_str(GENERATED_HEADER);
    out.push('\n');
    out.push_str("<!-- Source of truth: CRUX L8 memory (sqlite). -->\n");
    out.push_str("<!-- Hand edits to this file are overwritten on next export. -->\n");
    out.push_str(
        "<!-- To add memories: `crux remember --kind <kind> --title <t> --content <c>`. -->\n",
    );
    out.push('\n');
    out.push_str("# Memory\n\n");

    let when = DateTime::from_timestamp(generated_at_epoch, 0)
        .map(|dt| dt.format("%Y-%m-%d %H:%M:%SZ").to_string())
        .unwrap_or_else(|| format!("epoch={}", generated_at_epoch));
    out.push_str(&format!(
        "_Generated {} — {} observation{} from `{}`._\n\n",
        when,
        observations.len(),
        if observations.len() == 1 { "" } else { "s" },
        project_root
    ));

    if observations.is_empty() {
        out.push_str("_No observations recorded yet._\n");
        return out;
    }

    let groups = group_by_kind(observations);
    for kind in render_order() {
        let Some(items) = groups.get(&kind) else {
            continue;
        };
        if items.is_empty() {
            continue;
        }
        out.push_str(&format!("## {} ({})\n\n", kind_heading(kind), items.len()));
        for obs in items {
            render_one(&mut out, obs);
        }
    }

    out
}

fn render_order() -> [ObservationKind; 8] {
    [
        ObservationKind::Guardrail,
        ObservationKind::User,
        ObservationKind::Convention,
        ObservationKind::Decision,
        ObservationKind::Project,
        ObservationKind::Reference,
        ObservationKind::ErrorPattern,
        ObservationKind::Feedback,
    ]
}

fn kind_heading(k: ObservationKind) -> &'static str {
    match k {
        ObservationKind::Guardrail => "Guardrails",
        ObservationKind::User => "User preferences",
        ObservationKind::Convention => "Conventions",
        ObservationKind::Decision => "Decisions",
        ObservationKind::Project => "Project",
        ObservationKind::Reference => "References",
        ObservationKind::ErrorPattern => "Error patterns",
        ObservationKind::Feedback => "Feedback",
    }
}

fn group_by_kind(
    observations: &[Observation],
) -> std::collections::BTreeMap<ObservationKind, Vec<&Observation>> {
    use std::collections::BTreeMap;
    let mut by_kind: BTreeMap<ObservationKind, Vec<&Observation>> = BTreeMap::new();
    for o in observations {
        by_kind.entry(o.kind).or_default().push(o);
    }
    for v in by_kind.values_mut() {
        // Importance desc, then id desc — gives a stable, scannable order.
        v.sort_by(|a, b| {
            b.importance
                .cmp(&a.importance)
                .then_with(|| b.id.cmp(&a.id))
        });
    }
    by_kind
}

fn render_one(out: &mut String, obs: &Observation) {
    out.push_str(&format!(
        "### {} _(importance {})_\n\n",
        sanitize_title(&obs.title),
        obs.importance
    ));
    out.push_str(obs.content.trim_end());
    out.push_str("\n\n");

    if let Some(why) = &obs.why {
        if !why.trim().is_empty() {
            out.push_str("**Why:** ");
            out.push_str(why.trim());
            out.push_str("\n\n");
        }
    }
    if let Some(how) = &obs.how_to_apply {
        if !how.trim().is_empty() {
            out.push_str("**How to apply:** ");
            out.push_str(how.trim());
            out.push_str("\n\n");
        }
    }

    let mut footer_bits: Vec<String> = Vec::new();
    if let Some(sym) = &obs.symbol {
        if !sym.is_empty() {
            footer_bits.push(format!("symbol `{}`", sym));
        }
    }
    if let Some(file) = &obs.file_path {
        if !file.is_empty() {
            footer_bits.push(format!("file `{}`", file));
        }
    }
    if !obs.tags.is_empty() {
        let tags = obs
            .tags
            .iter()
            .map(|t| format!("`{}`", t))
            .collect::<Vec<_>>()
            .join(", ");
        footer_bits.push(format!("tags {}", tags));
    }
    footer_bits.push(format!("id #{}", obs.id));
    out.push_str("<sub>");
    out.push_str(&footer_bits.join(" · "));
    out.push_str("</sub>\n\n");
}

/// Strip newlines from titles so they stay on a single markdown heading
/// line. Anything else (including markdown specials) we leave alone —
/// the user wrote it and we should display it.
fn sanitize_title(t: &str) -> String {
    t.replace(['\n', '\r'], " ").trim().to_string()
}

// Disk I/O

/// Pull active observations for `project_root` from L8 and write a
/// rendered `MEMORY.md` to `target`. Atomic via `tmp + rename`. Refuses
/// to clobber a file that lacks our generated header unless
/// `opts.force` is set.
pub fn export_memory_md<'c>(
    engine: &MemoryEngine<'c>,
    project_root: &str,
    target: &Path,
    opts: &ExportOptions,
) -> Result<ExportReport> {
    let limit = opts.limit.unwrap_or(DEFAULT_EXPORT_LIMIT);
    let observations = engine.list(project_root, limit)?;
    let body = render_memory_md(&observations, project_root, chrono::Utc::now().timestamp());

    write_atomically(target, &body, opts.force, observations.len())
}

fn write_atomically(
    target: &Path,
    body: &str,
    force: bool,
    observations_rendered: usize,
) -> Result<ExportReport> {
    // Refuse to overwrite a non-generated MEMORY.md unless explicitly forced.
    if target.exists() && !force {
        match fs::read_to_string(target) {
            Ok(existing) => {
                if !existing.starts_with(GENERATED_HEADER) {
                    return Ok(ExportReport {
                        target: target.to_path_buf(),
                        observations_rendered,
                        bytes_written: 0,
                        unchanged: false,
                        refused_due_to_handwritten: true,
                    });
                }
                if existing == body {
                    // Same content — skip the disk churn. Important for
                    // any debounced caller (e.g., a memory-watch loop)
                    // that wants to call `export` after every `remember`
                    // without thrashing mtime.
                    return Ok(ExportReport {
                        target: target.to_path_buf(),
                        observations_rendered,
                        bytes_written: existing.len() as u64,
                        unchanged: true,
                        refused_due_to_handwritten: false,
                    });
                }
            }
            Err(_) => {
                // Unreadable existing file — let the write attempt below
                // surface a real OS error rather than guess at intent.
            }
        }
    }

    if let Some(parent) = target.parent() {
        if !parent.as_os_str().is_empty() {
            fs::create_dir_all(parent).map_err(|e| CruxError::Io {
                path: parent.to_path_buf(),
                source: e,
            })?;
        }
    }

    // Write to a sibling tmp file, fsync, rename. Same recipe used by
    // `crux-l10-setup`'s json_merge / yaml_merge helpers.
    let tmp = sibling_tmp_path(target);
    {
        let mut f = fs::File::create(&tmp).map_err(|e| CruxError::Io {
            path: tmp.clone(),
            source: e,
        })?;
        f.write_all(body.as_bytes()).map_err(|e| CruxError::Io {
            path: tmp.clone(),
            source: e,
        })?;
        f.sync_all().map_err(|e| CruxError::Io {
            path: tmp.clone(),
            source: e,
        })?;
    }
    fs::rename(&tmp, target).map_err(|e| CruxError::Io {
        path: target.to_path_buf(),
        source: e,
    })?;

    Ok(ExportReport {
        target: target.to_path_buf(),
        observations_rendered,
        bytes_written: body.len() as u64,
        unchanged: false,
        refused_due_to_handwritten: false,
    })
}

fn sibling_tmp_path(target: &Path) -> PathBuf {
    let stem = target
        .file_name()
        .map(|s| s.to_string_lossy().to_string())
        .unwrap_or_else(|| "MEMORY.md".to_string());
    let tmp_name = format!(".{stem}.crux-tmp");
    target
        .parent()
        .map(|p| p.join(&tmp_name))
        .unwrap_or_else(|| PathBuf::from(tmp_name))
}

// Tests

#[cfg(test)]
mod tests {
    use super::*;
    use crate::types::NewObservation;

    fn fixture_engine() -> rusqlite::Connection {
        crux_core::db::open_in_memory().unwrap()
    }

    fn project() -> &'static str {
        "/tmp/proj"
    }

    fn render_at_t0(obs: &[Observation]) -> String {
        // Fixed timestamp so tests don't drift.
        render_memory_md(obs, project(), 1_700_000_000)
    }

    #[test]
    fn render_empty_list_keeps_header_and_empty_marker() {
        let out = render_at_t0(&[]);
        assert!(out.starts_with(GENERATED_HEADER));
        assert!(out.contains("# Memory"));
        assert!(out.contains("No observations recorded yet"));
    }

    #[test]
    fn render_groups_by_kind_in_fixed_order() {
        let conn = fixture_engine();
        let mem = MemoryEngine::new(&conn).unwrap();
        let mut feedback = NewObservation::minimal(project(), ObservationKind::Feedback, "fb", "x");
        feedback.importance = 5;
        let mut guard = NewObservation::minimal(
            project(),
            ObservationKind::Guardrail,
            "never log secrets",
            "redact",
        );
        guard.importance = 9;
        let mut user = NewObservation::minimal(
            project(),
            ObservationKind::User,
            "speak Indonesian",
            "default lang",
        );
        user.importance = 7;
        mem.remember(feedback).unwrap();
        mem.remember(guard).unwrap();
        mem.remember(user).unwrap();

        let listed = mem.list(project(), 100).unwrap();
        let out = render_at_t0(&listed);

        let g = out.find("## Guardrails").unwrap();
        let u = out.find("## User preferences").unwrap();
        let f = out.find("## Feedback").unwrap();
        // Guardrails before User before Feedback — fixed order.
        assert!(g < u);
        assert!(u < f);
        assert!(out.contains("never log secrets"));
        assert!(out.contains("speak Indonesian"));
    }

    #[test]
    fn render_is_deterministic_for_same_inputs() {
        let conn = fixture_engine();
        let mem = MemoryEngine::new(&conn).unwrap();
        for i in 0..5 {
            let mut o = NewObservation::minimal(
                project(),
                ObservationKind::Decision,
                format!("title {i}"),
                format!("body {i}"),
            );
            o.importance = (i + 1) as u8;
            mem.remember(o).unwrap();
        }
        let listed = mem.list(project(), 100).unwrap();
        let a = render_at_t0(&listed);
        let b = render_at_t0(&listed);
        assert_eq!(a, b, "render should be deterministic");
    }

    #[test]
    fn export_writes_then_skips_when_unchanged() {
        let conn = fixture_engine();
        let mem = MemoryEngine::new(&conn).unwrap();
        mem.remember(NewObservation::minimal(
            project(),
            ObservationKind::User,
            "be terse",
            "no fluff",
        ))
        .unwrap();

        let dir = tempfile::tempdir().unwrap();
        let target = dir.path().join("MEMORY.md");
        let r1 = export_memory_md(&mem, project(), &target, &ExportOptions::default()).unwrap();
        assert!(!r1.unchanged);
        assert!(r1.bytes_written > 0);

        let r2 = export_memory_md(&mem, project(), &target, &ExportOptions::default()).unwrap();
        assert!(r2.unchanged, "second export must be a no-op (debounce)");
        assert!(!r2.refused_due_to_handwritten);
    }

    #[test]
    fn export_refuses_to_clobber_handwritten_memory_md() {
        let conn = fixture_engine();
        let mem = MemoryEngine::new(&conn).unwrap();
        mem.remember(NewObservation::minimal(
            project(),
            ObservationKind::User,
            "x",
            "y",
        ))
        .unwrap();

        let dir = tempfile::tempdir().unwrap();
        let target = dir.path().join("MEMORY.md");
        std::fs::write(&target, "# Hand-written notes\nNot generated.\n").unwrap();

        let r = export_memory_md(&mem, project(), &target, &ExportOptions::default()).unwrap();
        assert!(r.refused_due_to_handwritten);
        // File contents are unchanged.
        assert!(std::fs::read_to_string(&target)
            .unwrap()
            .starts_with("# Hand-written notes"));

        // ...but `force` overrides.
        let forced = export_memory_md(
            &mem,
            project(),
            &target,
            &ExportOptions {
                force: true,
                limit: None,
            },
        )
        .unwrap();
        assert!(!forced.refused_due_to_handwritten);
        assert!(std::fs::read_to_string(&target)
            .unwrap()
            .starts_with(GENERATED_HEADER));
    }

    #[test]
    fn export_creates_parent_dir() {
        let conn = fixture_engine();
        let mem = MemoryEngine::new(&conn).unwrap();
        mem.remember(NewObservation::minimal(
            project(),
            ObservationKind::Decision,
            "use rust",
            "perf",
        ))
        .unwrap();

        let dir = tempfile::tempdir().unwrap();
        let nested = dir.path().join("a").join("b").join("MEMORY.md");
        let r = export_memory_md(&mem, project(), &nested, &ExportOptions::default()).unwrap();
        assert!(nested.exists());
        assert!(r.bytes_written > 0);
    }
}
