use std::fs;
use std::io;
use std::path::{Path, PathBuf};

use crate::rules::{
    find_marketing_phrase, has_layer_label, has_pattern_adapted_from, is_decorative_banner,
    is_goal_header, is_public_surface_header, RuleId,
};
use crate::types::{HygieneOptions, HygieneReport, HygieneViolation, Severity};

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) enum Lang {
    Rust,
    Toml,
    Markdown,
    Yaml,
    JsTs,
    Python,
    Other,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) enum LineKind {
    Code,
    LineComment,
    BlockCommentLine,
    DocComment,
    ModuleDoc,
    MarkdownProse,
    MarkdownCode,
    Blank,
}

#[derive(Debug, Clone)]
pub(crate) struct ClassifiedLine {
    pub line_no: usize,
    pub raw: String,
    pub body: String,
    pub kind: LineKind,
}

pub fn scan_comments(root: &Path, options: &HygieneOptions) -> io::Result<HygieneReport> {
    let mut report = HygieneReport::default();
    let mut files: Vec<PathBuf> = Vec::new();
    walk(root, options, &mut files)?;
    files.sort();
    for file in &files {
        scan_file(file, options, &mut report);
    }
    Ok(report)
}

pub fn scan_paths<I, P>(paths: I, options: &HygieneOptions) -> io::Result<HygieneReport>
where
    I: IntoIterator<Item = P>,
    P: AsRef<Path>,
{
    let mut report = HygieneReport::default();
    for p in paths {
        let path = p.as_ref();
        if !is_eligible_file(path, options) {
            continue;
        }
        scan_file(path, options, &mut report);
    }
    Ok(report)
}

fn is_eligible_file(path: &Path, options: &HygieneOptions) -> bool {
    if !path.is_file() {
        return false;
    }
    if let Some(name) = path.file_name().and_then(|n| n.to_str()) {
        if options.ignored_files.iter().any(|f| f == name) {
            return false;
        }
    }
    let ext = path
        .extension()
        .and_then(|e| e.to_str())
        .unwrap_or("")
        .to_ascii_lowercase();
    if !options.include_extensions.iter().any(|e| e == &ext) {
        return false;
    }
    for component in path.components() {
        if let std::path::Component::Normal(os) = component {
            if let Some(name) = os.to_str() {
                if options.ignored_dirs.iter().any(|d| d == name) {
                    return false;
                }
            }
        }
    }
    true
}

fn scan_file(file: &Path, options: &HygieneOptions, report: &mut HygieneReport) {
    let content = match fs::read_to_string(file) {
        Ok(c) => c,
        Err(_) => return,
    };
    if is_generated(&content) {
        return;
    }
    report.files_scanned += 1;
    let lang = detect_lang(file);
    let lines = classify_lines(&content, lang);
    let before = report.violations.len();
    apply_rules(file, &lines, lang, options, &mut report.violations);
    if report.violations.len() > before {
        report.files_with_violations += 1;
    }
}

pub(crate) fn walk(dir: &Path, opts: &HygieneOptions, out: &mut Vec<PathBuf>) -> io::Result<()> {
    let ignored_dirs = opts.ignored_dirs.clone();
    let respect = opts.respect_gitignore;
    let walker = ignore::WalkBuilder::new(dir)
        .follow_links(opts.follow_symlinks)
        .hidden(false)
        .git_ignore(respect)
        .git_global(respect)
        .git_exclude(respect)
        .ignore(respect)
        .parents(respect)
        .filter_entry(move |entry| {
            if let Some(ft) = entry.file_type() {
                if ft.is_dir() {
                    if let Some(name) = entry.file_name().to_str() {
                        if ignored_dirs.iter().any(|d| d == name) {
                            return false;
                        }
                    }
                }
            }
            true
        })
        .build();
    for result in walker {
        let entry = match result {
            Ok(e) => e,
            Err(_) => continue,
        };
        let ft = match entry.file_type() {
            Some(f) => f,
            None => continue,
        };
        if !ft.is_file() {
            continue;
        }
        let path = entry.path();
        let name = match path.file_name().and_then(|n| n.to_str()) {
            Some(n) => n.to_string(),
            None => continue,
        };
        if opts.ignored_files.iter().any(|f| f == &name) {
            continue;
        }
        let ext = path
            .extension()
            .and_then(|e| e.to_str())
            .unwrap_or("")
            .to_ascii_lowercase();
        if !opts.include_extensions.iter().any(|e| e == &ext) {
            continue;
        }
        out.push(path.to_path_buf());
    }
    Ok(())
}

pub(crate) fn is_generated(content: &str) -> bool {
    let head: String = content.chars().take(800).collect();
    let lower = head.to_ascii_lowercase();
    lower.contains("@generated")
        || lower.contains("autogenerated")
        || lower.contains("auto-generated")
        || lower.contains("do not edit")
        || lower.contains("this file is generated")
}

pub(crate) fn detect_lang(p: &Path) -> Lang {
    match p
        .extension()
        .and_then(|e| e.to_str())
        .map(|s| s.to_ascii_lowercase())
        .as_deref()
    {
        Some("rs") => Lang::Rust,
        Some("toml") => Lang::Toml,
        Some("md") | Some("markdown") => Lang::Markdown,
        Some("yml") | Some("yaml") => Lang::Yaml,
        Some("js") | Some("jsx") | Some("ts") | Some("tsx") | Some("mjs") | Some("cjs") => {
            Lang::JsTs
        }
        Some("py") => Lang::Python,
        _ => Lang::Other,
    }
}

pub(crate) fn classify_lines(src: &str, lang: Lang) -> Vec<ClassifiedLine> {
    match lang {
        Lang::Rust | Lang::JsTs => classify_c_like(src, lang),
        Lang::Toml | Lang::Yaml => classify_hash(src),
        Lang::Markdown => classify_markdown(src),
        Lang::Python => classify_python(src),
        Lang::Other => Vec::new(),
    }
}

#[derive(Clone, Copy, PartialEq, Eq)]
enum CxState {
    Normal,
    InStr,
    InRawStr(usize),
    InBlock,
}

fn classify_c_like(src: &str, lang: Lang) -> Vec<ClassifiedLine> {
    let mut out = Vec::new();
    let mut state = CxState::Normal;
    for (i, raw) in src.split('\n').enumerate() {
        let (kind, body, next_state) = classify_c_line(raw, lang, state);
        out.push(ClassifiedLine {
            line_no: i + 1,
            raw: raw.to_string(),
            body,
            kind,
        });
        state = next_state;
    }
    out
}

fn classify_c_line(raw: &str, lang: Lang, enter: CxState) -> (LineKind, String, CxState) {
    let bytes = raw.as_bytes();

    if enter == CxState::InBlock {
        let body = strip_block_decoration(raw);
        let mut state = CxState::InBlock;
        let mut i = 0;
        while i < bytes.len() {
            i = advance_cx(bytes, i, &mut state);
            if state == CxState::Normal {
                break;
            }
        }
        while i < bytes.len() {
            i = advance_cx(bytes, i, &mut state);
        }
        return (LineKind::BlockCommentLine, body, state);
    }

    if matches!(enter, CxState::InStr | CxState::InRawStr(_)) {
        let mut state = enter;
        let mut i = 0;
        while i < bytes.len() {
            i = advance_cx(bytes, i, &mut state);
        }
        let kind = if raw.is_empty() {
            LineKind::Blank
        } else {
            LineKind::Code
        };
        return (kind, String::new(), state);
    }

    let lead_ws = raw
        .bytes()
        .take_while(|c| *c == b' ' || *c == b'\t')
        .count();
    if lead_ws == bytes.len() {
        return (LineKind::Blank, String::new(), CxState::Normal);
    }
    let rest = &raw[lead_ws..];

    if matches!(lang, Lang::Rust) {
        if let Some(after) = rest.strip_prefix("//!") {
            return (
                LineKind::ModuleDoc,
                after.trim_start().to_string(),
                CxState::Normal,
            );
        }
        if let Some(after) = rest.strip_prefix("///") {
            return (
                LineKind::DocComment,
                after.trim_start().to_string(),
                CxState::Normal,
            );
        }
    }
    if let Some(after) = rest.strip_prefix("//") {
        return (
            LineKind::LineComment,
            after.trim_start().to_string(),
            CxState::Normal,
        );
    }
    if rest.starts_with("/*") {
        let body_start = lead_ws + 2;
        if let Some(end_rel) = raw[body_start..].find("*/") {
            let body = raw[body_start..body_start + end_rel].trim().to_string();
            let mut state = CxState::Normal;
            let mut i = body_start + end_rel + 2;
            while i < bytes.len() {
                i = advance_cx(bytes, i, &mut state);
            }
            return (LineKind::BlockCommentLine, body, state);
        }
        let body = raw[body_start..].trim().to_string();
        return (LineKind::BlockCommentLine, body, CxState::InBlock);
    }

    let mut state = CxState::Normal;
    let mut i = 0;
    while i < bytes.len() {
        i = advance_cx(bytes, i, &mut state);
    }
    (LineKind::Code, String::new(), state)
}

fn advance_cx(bytes: &[u8], i: usize, state: &mut CxState) -> usize {
    match *state {
        CxState::Normal => {
            let c = bytes[i];
            if c == b'"' {
                *state = CxState::InStr;
                return i + 1;
            }
            if c == b'r' && is_raw_string_open(bytes, i) {
                let mut j = i + 1;
                let mut hashes = 0usize;
                while j < bytes.len() && bytes[j] == b'#' {
                    hashes += 1;
                    j += 1;
                }
                if j < bytes.len() && bytes[j] == b'"' {
                    *state = CxState::InRawStr(hashes);
                    return j + 1;
                }
                return i + 1;
            }
            if c == b'b' && i + 1 < bytes.len() && bytes[i + 1] == b'"' {
                *state = CxState::InStr;
                return i + 2;
            }
            if c == b'\'' {
                return skip_char_literal(bytes, i);
            }
            if c == b'/' && i + 1 < bytes.len() {
                if bytes[i + 1] == b'/' {
                    return bytes.len();
                }
                if bytes[i + 1] == b'*' {
                    *state = CxState::InBlock;
                    return i + 2;
                }
            }
            i + 1
        }
        CxState::InStr => {
            let c = bytes[i];
            if c == b'\\' && i + 1 < bytes.len() {
                return i + 2;
            }
            if c == b'"' {
                *state = CxState::Normal;
                return i + 1;
            }
            i + 1
        }
        CxState::InRawStr(n) => {
            if bytes[i] == b'"' {
                let mut j = i + 1;
                let mut seen = 0usize;
                while seen < n && j < bytes.len() && bytes[j] == b'#' {
                    seen += 1;
                    j += 1;
                }
                if seen == n {
                    *state = CxState::Normal;
                    return j;
                }
            }
            i + 1
        }
        CxState::InBlock => {
            if i + 1 < bytes.len() && bytes[i] == b'*' && bytes[i + 1] == b'/' {
                *state = CxState::Normal;
                return i + 2;
            }
            i + 1
        }
    }
}

fn is_raw_string_open(bytes: &[u8], i: usize) -> bool {
    if i > 0 {
        let prev = bytes[i - 1];
        if prev.is_ascii_alphanumeric() || prev == b'_' {
            return false;
        }
    }
    let mut j = i + 1;
    while j < bytes.len() && bytes[j] == b'#' {
        j += 1;
    }
    j < bytes.len() && bytes[j] == b'"'
}

fn skip_char_literal(bytes: &[u8], start: usize) -> usize {
    let mut j = start + 1;
    let limit = (start + 10).min(bytes.len());
    while j < limit {
        if bytes[j] == b'\\' && j + 1 < bytes.len() {
            j += 2;
            continue;
        }
        if bytes[j] == b'\'' {
            return j + 1;
        }
        j += 1;
    }
    start + 1
}

fn classify_hash(src: &str) -> Vec<ClassifiedLine> {
    let mut out = Vec::new();
    for (i, raw) in src.split('\n').enumerate() {
        let line_no = i + 1;
        let trim = raw.trim_start();
        if trim.is_empty() {
            out.push(ClassifiedLine {
                line_no,
                raw: raw.to_string(),
                body: String::new(),
                kind: LineKind::Blank,
            });
            continue;
        }
        if let Some(rest) = trim.strip_prefix('#') {
            out.push(ClassifiedLine {
                line_no,
                raw: raw.to_string(),
                body: rest.trim_start().to_string(),
                kind: LineKind::LineComment,
            });
            continue;
        }
        out.push(ClassifiedLine {
            line_no,
            raw: raw.to_string(),
            body: String::new(),
            kind: LineKind::Code,
        });
    }
    out
}

fn classify_markdown(src: &str) -> Vec<ClassifiedLine> {
    let mut out = Vec::new();
    let mut in_fence = false;
    for (i, raw) in src.split('\n').enumerate() {
        let line_no = i + 1;
        let trim = raw.trim_start();
        if trim.starts_with("```") || trim.starts_with("~~~") {
            out.push(ClassifiedLine {
                line_no,
                raw: raw.to_string(),
                body: String::new(),
                kind: LineKind::MarkdownCode,
            });
            in_fence = !in_fence;
            continue;
        }
        if in_fence {
            out.push(ClassifiedLine {
                line_no,
                raw: raw.to_string(),
                body: String::new(),
                kind: LineKind::MarkdownCode,
            });
            continue;
        }
        if trim.is_empty() {
            out.push(ClassifiedLine {
                line_no,
                raw: raw.to_string(),
                body: String::new(),
                kind: LineKind::Blank,
            });
            continue;
        }
        out.push(ClassifiedLine {
            line_no,
            raw: raw.to_string(),
            body: trim.to_string(),
            kind: LineKind::MarkdownProse,
        });
    }
    out
}

fn classify_python(src: &str) -> Vec<ClassifiedLine> {
    let mut out = Vec::new();
    let mut in_triple_double = false;
    let mut in_triple_single = false;
    for (i, raw) in src.split('\n').enumerate() {
        let line_no = i + 1;
        let trim = raw.trim_start();
        if in_triple_double {
            let still_in = !raw.contains("\"\"\"");
            out.push(ClassifiedLine {
                line_no,
                raw: raw.to_string(),
                body: trim.trim_end_matches("\"\"\"").to_string(),
                kind: LineKind::ModuleDoc,
            });
            in_triple_double = still_in;
            continue;
        }
        if in_triple_single {
            let still_in = !raw.contains("'''");
            out.push(ClassifiedLine {
                line_no,
                raw: raw.to_string(),
                body: trim.trim_end_matches("'''").to_string(),
                kind: LineKind::ModuleDoc,
            });
            in_triple_single = still_in;
            continue;
        }
        if trim.is_empty() {
            out.push(ClassifiedLine {
                line_no,
                raw: raw.to_string(),
                body: String::new(),
                kind: LineKind::Blank,
            });
            continue;
        }
        if let Some(rest) = trim.strip_prefix('#') {
            out.push(ClassifiedLine {
                line_no,
                raw: raw.to_string(),
                body: rest.trim_start().to_string(),
                kind: LineKind::LineComment,
            });
            continue;
        }
        if let Some(after) = trim.strip_prefix("\"\"\"") {
            let closes = after.contains("\"\"\"");
            in_triple_double = !closes;
            out.push(ClassifiedLine {
                line_no,
                raw: raw.to_string(),
                body: after.trim_end_matches("\"\"\"").trim().to_string(),
                kind: LineKind::ModuleDoc,
            });
            continue;
        }
        if let Some(after) = trim.strip_prefix("'''") {
            let closes = after.contains("'''");
            in_triple_single = !closes;
            out.push(ClassifiedLine {
                line_no,
                raw: raw.to_string(),
                body: after.trim_end_matches("'''").trim().to_string(),
                kind: LineKind::ModuleDoc,
            });
            continue;
        }
        out.push(ClassifiedLine {
            line_no,
            raw: raw.to_string(),
            body: String::new(),
            kind: LineKind::Code,
        });
    }
    out
}

fn strip_block_decoration(raw: &str) -> String {
    let trim = raw.trim_start();
    let body = trim
        .trim_start_matches('*')
        .trim_start_matches([' ', '\t'])
        .trim_end_matches("*/")
        .trim_end();
    body.to_string()
}

fn is_safety_comment(body: &str) -> bool {
    let head = body.trim_start();
    let lower = head.to_ascii_lowercase();
    lower.starts_with("safety:")
        || lower.starts_with("unsafe:")
        || lower.starts_with("security:")
        || lower.starts_with("warning:")
        || lower.starts_with("todo:")
        || lower.starts_with("fixme:")
        || lower.starts_with("xxx:")
        || lower.starts_with("hack:")
        || lower.starts_with("note:")
}

pub(crate) fn is_comment_kind(k: &LineKind) -> bool {
    matches!(
        k,
        LineKind::LineComment
            | LineKind::BlockCommentLine
            | LineKind::DocComment
            | LineKind::ModuleDoc
    )
}

fn is_phrase_target(k: &LineKind) -> bool {
    is_comment_kind(k) || matches!(k, LineKind::MarkdownProse)
}

fn apply_rules(
    file: &Path,
    lines: &[ClassifiedLine],
    lang: Lang,
    options: &HygieneOptions,
    out: &mut Vec<HygieneViolation>,
) {
    for ln in lines {
        if !is_phrase_target(&ln.kind) {
            continue;
        }
        if is_safety_comment(&ln.body) {
            continue;
        }
        if is_comment_kind(&ln.kind) && is_decorative_banner(&ln.body, options.min_banner_run) {
            out.push(violation(
                file,
                ln,
                RuleId::DecorativeBanner,
                Severity::Error,
                "decorative banner comment",
                Some("(remove)".to_string()),
            ));
            continue;
        }
        if is_goal_header(&ln.body) {
            out.push(violation(
                file,
                ln,
                RuleId::GoalSection,
                Severity::Error,
                "`Goal:` section in source",
                Some("(remove; document in README)".to_string()),
            ));
            continue;
        }
        if is_public_surface_header(&ln.body) {
            out.push(violation(
                file,
                ln,
                RuleId::PublicSurfaceSection,
                Severity::Error,
                "`Public surface:` block",
                Some("(remove; `pub use` is the surface)".to_string()),
            ));
            continue;
        }
        if has_pattern_adapted_from(&ln.body) {
            out.push(violation(
                file,
                ln,
                RuleId::PatternAdaptedFrom,
                Severity::Warn,
                "`Pattern adapted from` reference",
                Some("(move to commit message)".to_string()),
            ));
            continue;
        }
        if is_comment_kind(&ln.kind) && has_layer_label(&ln.body) {
            out.push(violation(
                file,
                ln,
                RuleId::LayerLabel,
                Severity::Warn,
                "`Layer N` label duplicates ARCHITECTURE.md",
                Some("(remove or shorten)".to_string()),
            ));
            continue;
        }
        if let Some(p) = find_marketing_phrase(&ln.body) {
            out.push(violation(
                file,
                ln,
                RuleId::MarketingPhrase,
                Severity::Warn,
                &format!("marketing phrase `{p}`"),
                Some("(remove or rephrase)".to_string()),
            ));
            continue;
        }
    }
    if matches!(lang, Lang::Rust) {
        flag_long_module_doc_runs(file, lines, options, out);
    }
}

fn flag_long_module_doc_runs(
    file: &Path,
    lines: &[ClassifiedLine],
    options: &HygieneOptions,
    out: &mut Vec<HygieneViolation>,
) {
    let mut i = 0;
    while i < lines.len() {
        if lines[i].kind != LineKind::ModuleDoc {
            i += 1;
            continue;
        }
        let start = i;
        while i < lines.len() && lines[i].kind == LineKind::ModuleDoc {
            i += 1;
        }
        let run_len = i - start;
        if run_len > options.max_module_doc_lines {
            let first = &lines[start];
            out.push(HygieneViolation {
                file: file.to_path_buf(),
                line: first.line_no,
                rule_id: RuleId::LongModuleDoc.as_str().to_string(),
                severity: Severity::Error,
                reason: format!(
                    "module doc run is {} lines (max {})",
                    run_len, options.max_module_doc_lines
                ),
                snippet: first.raw.trim_end().to_string(),
                suggested_replacement: Some("(compress to one short sentence)".to_string()),
            });
        }
    }
}

fn violation(
    file: &Path,
    ln: &ClassifiedLine,
    rule: RuleId,
    sev: Severity,
    reason: &str,
    suggestion: Option<String>,
) -> HygieneViolation {
    HygieneViolation {
        file: file.to_path_buf(),
        line: ln.line_no,
        rule_id: rule.as_str().to_string(),
        severity: sev,
        reason: reason.to_string(),
        snippet: ln.raw.trim_end().to_string(),
        suggested_replacement: suggestion,
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::io::Write;

    fn write(dir: &Path, name: &str, body: &str) -> PathBuf {
        let p = dir.join(name);
        if let Some(parent) = p.parent() {
            std::fs::create_dir_all(parent).unwrap();
        }
        let mut f = std::fs::File::create(&p).unwrap();
        f.write_all(body.as_bytes()).unwrap();
        p
    }

    #[test]
    fn rust_module_doc_long_run_is_flagged() {
        let dir = tempfile::tempdir().unwrap();
        let body = "\
//! Title.
//!
//! Goal: ship the feature.
//!
//! Public surface:
//!
//! - foo
//! - bar
fn main() {}
";
        write(dir.path(), "src.rs", body);
        let opts = HygieneOptions {
            max_module_doc_lines: 3,
            ..HygieneOptions::for_root(dir.path())
        };
        let report = scan_comments(dir.path(), &opts).unwrap();
        assert!(!report.is_clean());
        let ids: Vec<_> = report
            .violations
            .iter()
            .map(|v| v.rule_id.clone())
            .collect();
        assert!(ids.iter().any(|i| i == "long-module-doc"));
        assert!(ids.iter().any(|i| i == "goal-section"));
        assert!(ids.iter().any(|i| i == "public-surface-section"));
    }

    #[test]
    fn toml_decorative_banner_is_flagged() {
        let dir = tempfile::tempdir().unwrap();
        write(
            dir.path(),
            "config.toml",
            "# ─────────────────────────────\n# Helpers\nkey = \"v\"\n",
        );
        let opts = HygieneOptions::for_root(dir.path());
        let report = scan_comments(dir.path(), &opts).unwrap();
        assert!(report
            .violations
            .iter()
            .any(|v| v.rule_id == "decorative-banner"));
    }

    #[test]
    fn markdown_code_block_preserved() {
        let dir = tempfile::tempdir().unwrap();
        write(
            dir.path(),
            "doc.md",
            "intro\n\n```rust\n// revolutionary cutting-edge example\nfn x() {}\n```\nend.\n",
        );
        let opts = HygieneOptions::for_root(dir.path());
        let report = scan_comments(dir.path(), &opts).unwrap();
        assert!(report.is_clean(), "got: {:?}", report.violations);
    }

    #[test]
    fn markdown_prose_marketing_phrase_flagged() {
        let dir = tempfile::tempdir().unwrap();
        write(
            dir.path(),
            "doc.md",
            "Our revolutionary, cutting-edge platform.\n",
        );
        let opts = HygieneOptions::for_root(dir.path());
        let report = scan_comments(dir.path(), &opts).unwrap();
        assert!(report
            .violations
            .iter()
            .any(|v| v.rule_id == "marketing-phrase"));
    }

    #[test]
    fn ignored_dirs_skipped() {
        let dir = tempfile::tempdir().unwrap();
        write(
            &dir.path().join("target"),
            "junk.rs",
            "//! Goal: this should be skipped.\n",
        );
        write(dir.path(), "ok.rs", "fn ok() {}\n");
        let opts = HygieneOptions::for_root(dir.path());
        let report = scan_comments(dir.path(), &opts).unwrap();
        assert!(report.is_clean());
    }

    #[test]
    fn generated_file_skipped() {
        let dir = tempfile::tempdir().unwrap();
        write(
            dir.path(),
            "auto.rs",
            "//! @generated\n//! Goal: skipped\n//! ────────────\nfn x() {}\n",
        );
        let opts = HygieneOptions::for_root(dir.path());
        let report = scan_comments(dir.path(), &opts).unwrap();
        assert_eq!(report.files_scanned, 0, "got: {:?}", report.violations);
    }

    #[test]
    fn safety_comment_preserved() {
        let dir = tempfile::tempdir().unwrap();
        write(
            dir.path(),
            "safe.rs",
            "// SAFETY: ────────── invariant: ptr is non-null\nfn x() {}\n",
        );
        let opts = HygieneOptions::for_root(dir.path());
        let report = scan_comments(dir.path(), &opts).unwrap();
        assert!(report.is_clean());
    }

    #[test]
    fn layer_label_flagged() {
        let dir = tempfile::tempdir().unwrap();
        write(
            dir.path(),
            "src.rs",
            "// Layer 1 read cache helper.\nfn x() {}\n",
        );
        let opts = HygieneOptions::for_root(dir.path());
        let report = scan_comments(dir.path(), &opts).unwrap();
        assert!(report.violations.iter().any(|v| v.rule_id == "layer-label"));
    }

    #[test]
    fn js_block_comment_marketing_flagged() {
        let dir = tempfile::tempdir().unwrap();
        write(
            dir.path(),
            "x.ts",
            "/* Our revolutionary product seamlessly integrates. */\nexport const x = 1;\n",
        );
        let opts = HygieneOptions::for_root(dir.path());
        let report = scan_comments(dir.path(), &opts).unwrap();
        assert!(report
            .violations
            .iter()
            .any(|v| v.rule_id == "marketing-phrase"));
    }

    #[test]
    fn python_module_docstring_long_doc_not_flagged_by_long_module_rule() {
        let dir = tempfile::tempdir().unwrap();
        let body = "\
\"\"\"Module top.

Goal: make it work.

Public surface: foo, bar.

Layer 1 module.
\"\"\"
def x():
    pass
";
        write(dir.path(), "m.py", body);
        let opts = HygieneOptions::for_root(dir.path());
        let report = scan_comments(dir.path(), &opts).unwrap();
        let ids: Vec<_> = report
            .violations
            .iter()
            .map(|v| v.rule_id.clone())
            .collect();
        assert!(ids.iter().any(|i| i == "goal-section"));
        assert!(ids.iter().any(|i| i == "public-surface-section"));
        assert!(ids.iter().any(|i| i == "layer-label"));
        assert!(!ids.iter().any(|i| i == "long-module-doc"));
    }

    #[test]
    fn scan_paths_flags_explicit_file() {
        let dir = tempfile::tempdir().unwrap();
        let rs = write(
            dir.path(),
            "src.rs",
            "// ─────────────────────────────\n// banner\nfn x() {}\n",
        );
        let opts = HygieneOptions::for_root(dir.path());
        let report = scan_paths([rs.as_path()], &opts).unwrap();
        assert_eq!(report.files_scanned, 1);
        assert!(report
            .violations
            .iter()
            .any(|v| v.rule_id == "decorative-banner"));
    }

    #[test]
    fn scan_paths_ignores_unsupported_extension() {
        let dir = tempfile::tempdir().unwrap();
        let p = write(dir.path(), "readme.txt", "anything\n");
        let opts = HygieneOptions::for_root(dir.path());
        let report = scan_paths([p.as_path()], &opts).unwrap();
        assert_eq!(report.files_scanned, 0);
        assert!(report.is_clean());
    }

    #[test]
    fn scan_paths_ignores_path_in_ignored_dir() {
        let dir = tempfile::tempdir().unwrap();
        let junk = write(
            &dir.path().join("target"),
            "junk.rs",
            "//! Goal: nope.\nfn x() {}\n",
        );
        let opts = HygieneOptions::for_root(dir.path());
        let report = scan_paths([junk.as_path()], &opts).unwrap();
        assert_eq!(report.files_scanned, 0);
        assert!(report.is_clean());
    }

    #[test]
    fn scan_paths_skips_generated_files() {
        let dir = tempfile::tempdir().unwrap();
        let gen = write(
            dir.path(),
            "gen.rs",
            "//! @generated\n//! Goal: should be skipped.\nfn x() {}\n",
        );
        let opts = HygieneOptions::for_root(dir.path());
        let report = scan_paths([gen.as_path()], &opts).unwrap();
        assert_eq!(report.files_scanned, 0);
        assert!(report.is_clean());
    }

    #[test]
    fn scan_paths_silently_skips_nonexistent() {
        let dir = tempfile::tempdir().unwrap();
        let missing = dir.path().join("nope.rs");
        let opts = HygieneOptions::for_root(dir.path());
        let report = scan_paths([missing.as_path()], &opts).unwrap();
        assert_eq!(report.files_scanned, 0);
        assert!(report.is_clean());
    }

    #[test]
    fn scan_paths_ignores_lockfile_by_name() {
        let dir = tempfile::tempdir().unwrap();
        let p = write(
            dir.path(),
            "Cargo.lock",
            "# ────────\n# banner\nkey = 'v'\n",
        );
        let opts = HygieneOptions::for_root(dir.path());
        let report = scan_paths([p.as_path()], &opts).unwrap();
        assert_eq!(report.files_scanned, 0);
    }

    #[test]
    fn scan_paths_accepts_multiple_files() {
        let dir = tempfile::tempdir().unwrap();
        let ok = write(dir.path(), "ok.rs", "fn ok() {}\n");
        let bad = write(dir.path(), "bad.rs", "// Layer 1 helper.\nfn bad() {}\n");
        let opts = HygieneOptions::for_root(dir.path());
        let report = scan_paths([ok.as_path(), bad.as_path()], &opts).unwrap();
        assert_eq!(report.files_scanned, 2);
        assert!(report.violations.iter().any(|v| v.rule_id == "layer-label"));
    }

    #[test]
    fn module_doc_inside_string_literal_is_not_flagged() {
        let dir = tempfile::tempdir().unwrap();
        let body = r###"fn fixture() {
    let body = "\
//! CRUX Layer 10 — setup scaffolding.
//!
//! Goal: exercise the scanner.
//!
//! Public surface:
//! - foo
//! - bar
//! ────────────────────────────────
fn inner() {}
";
    drop(body);
}
"###;
        write(dir.path(), "src.rs", body);
        let opts = HygieneOptions::for_root(dir.path());
        let report = scan_comments(dir.path(), &opts).unwrap();
        assert!(
            report.is_clean(),
            "expected no violations inside a string literal, got: {:?}",
            report.violations
        );
    }

    #[test]
    fn raw_string_hides_comment_shaped_text() {
        let dir = tempfile::tempdir().unwrap();
        let body = r####"fn fixture() {
    let body = r#"
//! Goal: ship the feature.
// ────────────────────────────────
fn inner() {}
"#;
    drop(body);
}
"####;
        write(dir.path(), "src.rs", body);
        let opts = HygieneOptions::for_root(dir.path());
        let report = scan_comments(dir.path(), &opts).unwrap();
        assert!(
            report.is_clean(),
            "raw-string contents must not be flagged, got: {:?}",
            report.violations
        );
    }

    #[test]
    fn raw_string_with_two_hashes_closes_correctly() {
        let dir = tempfile::tempdir().unwrap();
        let body = r######"fn fixture() {
    let s = r##"
// Layer 1 helper "# still inside
//! Goal: still inside
"##;
    drop(s);
    // This real comment must still be flagged.
    // Layer 3 real helper.
    fn x() {}
}
"######;
        write(dir.path(), "src.rs", body);
        let opts = HygieneOptions::for_root(dir.path());
        let report = scan_comments(dir.path(), &opts).unwrap();
        let ids: Vec<_> = report
            .violations
            .iter()
            .map(|v| v.rule_id.clone())
            .collect();
        assert!(ids.iter().any(|i| i == "layer-label"));
        let layer_hits = ids.iter().filter(|i| *i == "layer-label").count();
        assert_eq!(layer_hits, 1, "got: {:?}", report.violations);
    }

    #[test]
    fn double_quote_inside_char_literal_does_not_open_string() {
        let dir = tempfile::tempdir().unwrap();
        let body = r###"fn fixture() {
    let c = '"';
    // Layer 1 helper — real comment.
    let _ = c;
}
"###;
        write(dir.path(), "src.rs", body);
        let opts = HygieneOptions::for_root(dir.path());
        let report = scan_comments(dir.path(), &opts).unwrap();
        assert!(report.violations.iter().any(|v| v.rule_id == "layer-label"));
    }

    #[test]
    fn escaped_quote_keeps_string_open() {
        let dir = tempfile::tempdir().unwrap();
        let body = "fn fixture() {\n    let s = \"open \\\"still open\n//! Goal: inside still\n\";\n    drop(s);\n}\n";
        write(dir.path(), "src.rs", body);
        let opts = HygieneOptions::for_root(dir.path());
        let report = scan_comments(dir.path(), &opts).unwrap();
        assert!(
            report.is_clean(),
            "escaped quote must not close the string, got: {:?}",
            report.violations
        );
    }

    #[test]
    fn real_comments_still_flagged_after_string_awareness() {
        let dir = tempfile::tempdir().unwrap();
        let body = "\
//! Title.
//!
//! Goal: ship.
//!
//! Public surface:
//!
//! - foo
//! - bar
fn main() {}
";
        write(dir.path(), "real.rs", body);
        let opts = HygieneOptions {
            max_module_doc_lines: 3,
            ..HygieneOptions::for_root(dir.path())
        };
        let report = scan_comments(dir.path(), &opts).unwrap();
        let ids: Vec<_> = report
            .violations
            .iter()
            .map(|v| v.rule_id.clone())
            .collect();
        assert!(ids.iter().any(|i| i == "long-module-doc"));
        assert!(ids.iter().any(|i| i == "goal-section"));
        assert!(ids.iter().any(|i| i == "public-surface-section"));
    }

    #[test]
    fn byte_string_literal_hides_comment_shaped_text() {
        let dir = tempfile::tempdir().unwrap();
        let body = "fn fixture() {\n    let _b = b\"\\\n//! Goal: bytes.\n\";\n}\n";
        write(dir.path(), "src.rs", body);
        let opts = HygieneOptions::for_root(dir.path());
        let report = scan_comments(dir.path(), &opts).unwrap();
        assert!(
            report.is_clean(),
            "byte-string content must not be flagged, got: {:?}",
            report.violations
        );
    }

    #[test]
    fn identifier_starting_with_r_is_not_raw_string() {
        let dir = tempfile::tempdir().unwrap();
        let body =
            "fn fixture(raw_hits: u32) -> u32 {\n    // Layer 2 helper.\n    return raw_hits;\n}\n";
        write(dir.path(), "src.rs", body);
        let opts = HygieneOptions::for_root(dir.path());
        let report = scan_comments(dir.path(), &opts).unwrap();
        assert!(report.violations.iter().any(|v| v.rule_id == "layer-label"));
    }

    #[test]
    fn layer_label_not_flagged_in_markdown_prose() {
        let dir = tempfile::tempdir().unwrap();
        let body = "# Architecture\n\nLayer 1 read cache.\nLayer 2 MCP shrink.\n";
        write(dir.path(), "ARCHITECTURE.md", body);
        let opts = HygieneOptions::for_root(dir.path());
        let report = scan_comments(dir.path(), &opts).unwrap();
        assert!(
            !report.violations.iter().any(|v| v.rule_id == "layer-label"),
            "markdown prose is the canonical source; got: {:?}",
            report.violations
        );
    }
}
