pub const STRIKE_PHRASES: &[&str] = &[
    r"in conclusion,?",
    r"to summarize,?",
    r"in summary,?",
    r"first and foremost,?",
    r"last but not least,?",
    r"it is important to note that",
    r"it's important to note that",
    r"it is worth noting that",
    r"it's worth noting that",
    r"it should be noted that",
    r"it must be noted that",
    r"needless to say,?",
    r"it goes without saying,?",
    r"at the end of the day,?",
    r"as previously mentioned,?",
    r"as mentioned earlier,?",
    r"as mentioned above,?",
    r"as mentioned before,?",
    r"in the realm of",
    r"in today's fast-paced world,?",
    r"in this day and age,?",
    r"in the world of",
    r"in this article,?",
    r"in this post,?",
    r"in this tutorial,?",
    r"in this guide,?",
    r"in this section,?",
    r"in this blog post,?",
    r"navigate the complexities of",
    r"embark on a journey",
    r"embark on the journey",
    r"as an AI language model,?",
    r"as a large language model,?",
    r"as an AI,?",
    r"being an AI,?",
    r"I hope this helps[!.]?",
    r"I hope this answers your question[!.]?",
    r"I hope that helps[!.]?",
    r"feel free to ask[!.]?",
    r"feel free to ask any other questions[!.]?",
    r"please let me know if you have any questions[!.]?",
    r"please let me know if you need anything else[!.]?",
    r"let's dive in[!.]?",
    r"let us dive in[!.]?",
    r"let's dive deep[!.]?",
    r"let's get started[!.]?",
];

pub const PHRASE_SUBS: &[(&str, &str)] = &[
    ("in order to", "to"),
    ("due to the fact that", "because"),
    ("at this point in time", "now"),
    ("at this moment in time", "now"),
    ("a number of", "several"),
    ("a large number of", "many"),
    ("a small number of", "few"),
    ("the majority of", "most"),
    ("with regard to", "about"),
    ("with regards to", "about"),
    ("in regards to", "about"),
    ("in regard to", "about"),
    ("for the purpose of", "to"),
    ("in spite of the fact that", "although"),
    ("on the grounds that", "because"),
    ("in the event that", "if"),
    ("a wide variety of", "many"),
    ("a wide range of", "many"),
    ("the fact that", "that"),
    ("with respect to", "about"),
    ("prior to", "before"),
    ("subsequent to", "after"),
    ("in the process of", "while"),
    ("has the ability to", "can"),
    ("have the ability to", "can"),
    ("is able to", "can"),
    ("are able to", "can"),
    ("in order for", "for"),
    ("I'll walk you through", "walk through"),
    ("I will walk you through", "walk through"),
    ("let me walk you through", "walk through"),
    ("I'll show you how to", "to"),
    ("let me show you how to", "to"),
];

pub const WORD_SUBS: &[(&str, &str)] = &[
    ("utilize", "use"),
    ("utilizes", "uses"),
    ("utilized", "used"),
    ("utilizing", "using"),
    ("utilization", "use"),
    ("facilitate", "help"),
    ("facilitates", "helps"),
    ("facilitated", "helped"),
    ("facilitating", "helping"),
    ("leverage", "use"),
    ("leverages", "uses"),
    ("leveraged", "used"),
    ("leveraging", "using"),
    ("commence", "start"),
    ("commences", "starts"),
    ("commenced", "started"),
    ("commencing", "starting"),
    ("terminate", "end"),
    ("terminates", "ends"),
    ("terminated", "ended"),
    ("terminating", "ending"),
    ("endeavor", "try"),
    ("endeavors", "tries"),
    ("endeavored", "tried"),
    ("endeavoring", "trying"),
    ("delve", "dig"),
    ("delves", "digs"),
    ("delved", "dug"),
    ("delving", "digging"),
    ("furthermore", "also"),
    ("moreover", "also"),
    ("nevertheless", "still"),
    ("nonetheless", "still"),
    ("subsequently", "then"),
    ("approximately", "about"),
    ("numerous", "many"),
    ("aforementioned", "this"),
    ("plethora", "lots"),
    ("myriad", "many"),
];

pub const FLUFF_ADJECTIVES: &[&str] = &[
    "robust",
    "comprehensive",
    "seamless",
    "seamlessly",
    "meticulous",
    "meticulously",
    "groundbreaking",
    "cutting-edge",
    "state-of-the-art",
    "best-in-class",
    "world-class",
    "next-generation",
    "next-gen",
    "game-changing",
    "game-changer",
    "synergistic",
    "synergy",
    "synergies",
    "holistic",
    "paradigm-shifting",
    "paradigm shift",
    "revolutionary",
    "transformative",
];

pub const PLEASANTRY_OPENERS: &[&str] = &[
    r"I'd be happy to help you with that[!.?,]?",
    r"I'd be happy to help with that[!.?,]?",
    r"I would be happy to help you with that[!.?,]?",
    r"I would be happy to help with that[!.?,]?",
    r"I'm happy to help you with that[!.?,]?",
    r"I am happy to help you with that[!.?,]?",
    r"You're absolutely right[!.?,]?",
    r"You make a great point[!.?,]?",
    r"That's a great question[!.?,]?",
    r"That's a good question[!.?,]?",
    r"That's a great point[!.?,]?",
    r"Excellent question[!.?,]?",
    r"I'd be happy to help[!.?,]?",
    r"I would be happy to help[!.?,]?",
    r"I'm happy to help[!.?,]?",
    r"I am happy to help[!.?,]?",
    r"Sure,? I can help[!.?,]?",
    r"Sure,? I'd be glad to[!.?,]?",
    r"Great question[!.?,]?",
    r"Good question[!.?,]?",
    r"You're right[!.?,]?",
    r"That's right[!.?,]?",
    r"That's correct[!.?,]?",
    r"Great point[!.?,]?",
    r"Good point[!.?,]?",
    r"Of course[!,.?]?",
    r"Absolutely[!,.?]?",
    r"Certainly[!,.?]?",
    r"Sure[!,.?]?",
];

pub const FILLER_WORDS: &[&str] = &[
    "basically",
    "just",
    "really",
    "very",
    "actually",
    "simply",
    "clearly",
];

pub const CONTRACTIONS: &[(&str, &str)] = &[
    (r"\bit is\b", "it's"),
    (r"\bIt is\b", "It's"),
    (r"\bdo not\b", "don't"),
    (r"\bDo not\b", "Don't"),
    (r"\bdoes not\b", "doesn't"),
    (r"\bDoes not\b", "Doesn't"),
    (r"\bdid not\b", "didn't"),
    (r"\bDid not\b", "Didn't"),
    (r"\bis not\b", "isn't"),
    (r"\bIs not\b", "Isn't"),
    (r"\bwas not\b", "wasn't"),
    (r"\bWas not\b", "Wasn't"),
    (r"\bwere not\b", "weren't"),
    (r"\bWere not\b", "Weren't"),
    (r"\bhas not\b", "hasn't"),
    (r"\bHas not\b", "Hasn't"),
    (r"\bhave not\b", "haven't"),
    (r"\bHave not\b", "Haven't"),
    (r"\bhad not\b", "hadn't"),
    (r"\bHad not\b", "Hadn't"),
    (r"\bcannot\b", "can't"),
    (r"\bCannot\b", "Can't"),
    (r"\bwill not\b", "won't"),
    (r"\bWill not\b", "Won't"),
    (r"\bwould not\b", "wouldn't"),
    (r"\bWould not\b", "Wouldn't"),
    (r"\bcould not\b", "couldn't"),
    (r"\bCould not\b", "Couldn't"),
    (r"\bshould not\b", "shouldn't"),
    (r"\bShould not\b", "Shouldn't"),
    (r"\bI am\b", "I'm"),
    (r"\bwe are\b", "we're"),
    (r"\bWe are\b", "We're"),
    (r"\bthey are\b", "they're"),
    (r"\bThey are\b", "They're"),
    (r"\byou are\b", "you're"),
    (r"\bYou are\b", "You're"),
    (r"\bthat is\b", "that's"),
    (r"\bThat is\b", "That's"),
    (r"\bthere is\b", "there's"),
    (r"\bThere is\b", "There's"),
];
