//! CRUX Layer 11 — conversation digest.
//!
//! Long-running agent sessions hoard tool-call results inside the model's
//! context window. By the 50th read+edit+search the prefix is mostly
//! historical noise. L11 attacks that vector by keeping a per-tool-call
//! log, then rolling old events into compact `turn_digests` that cost
//! ~10–20 lines instead of the original kilobytes.
//!
//! The flow is purely deterministic Rust — no LLM round-trip:
//!
//! 1. `crux hook post-tool` (or any direct caller) calls
//!    [`DigestEngine::record`] with a [`TurnEvent`].
//! 2. When the pending-event count for a session reaches
//!    `L11Config.auto_compact_every_n` the engine flushes them into a
//!    [`TurnDigest`] row and (optionally) mirrors the digest into the
//!    L8 memory store as a `convention` observation.
//! 3. Agents that need history call `crux digest` / `crux_digest`,
//!    which renders the most recent rollups + still-pending events.
//!
//! The summary is generated by [`render::render`] using a small
//! template system that groups events by tool family (read/edit/bash/
//! search/etc.). Adding new groupings is a match-arm change in
//! [`render::Bucket`].

pub mod engine;
pub mod render;
pub mod types;

pub use engine::DigestEngine;
pub use render::render;
pub use types::{L11Config, TurnDigest, TurnEvent, TurnStatus};
